---
title: "Presentation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Presentation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
# options(scipen = 9999)
# library(devtools)
# #install_github("guadag12/politicxsentwitteR")
# library(politicxsentwitteR)

```

1. Lista de usuarios que contiene [Politicxs en twitter]()

Podemos ver la lista que tenemos de funcionarios con *politicxs_data*:
```{r}
#head(politicxs_data)
```

2. Timelines:

a. Podemos descargar sobre un funcionario determinado
```{r}
# timeline_mev <- get_timeline_data("mariuvidal")
# head(timeline_mev)
```
E incluso saber cuándo fue que más twitteó:
```{r}
#library(tidyverse)
#library(plotly)
#library(hrbrthemes)

# p <- timeline_mev %>%
#         group_by(date=as.Date(created_at)) %>%
#         summarise(value = n()) %>%
#         ggplot( aes(x=date, y=value)) +
#           geom_area(fill="#dbb012", alpha=0.5) +
#           geom_line(color="#dbb012") +
#           ylab("Tweets emitidos por @mariuvidal") +
#           theme_ipsum()
# p <- ggplotly(p)
# p
```
E incluso podemos ver más de el estado de más de cuenta:

```{r}
#timeline_mev_mm <- get_timeline_data(screen.name = c("mariuvidal", "alferdez"))
#head(timeline_mev_mm)
#unique(timeline_mev_mm$user_id)
```
E incluso podemos ver cuántos amigos tiene cada uno:
```{r}
# foll_mev_mm <- get_friends_followers(screen.name = c("mariuvidal", "alferdez"))
# foll_mev_mm %>%
#         group_by(date=as.Date(date)) %>%
#         summarise(value = n()) %>%
#         ggplot( aes(x=date, y=value, fill = )) +
#           geom_area(fill="#dbb012", alpha=0.5) +
#           geom_line(color="#dbb012") +
#           ylab("Tweets emitidos por @mariuvidal") +
#           theme_ipsum()
```




